AlwaysPPS/trunk/AlwaysPPS.Web/Controllers/ReportFormController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlwaysFramework.DAL;
using AlwaysFramework.DAL.Providers.EntityFramework;
using AlwaysFramework.MVC;
using AlwaysFramework.MVC.Extension;
using AlwaysPPS.Data;
using AlwaysPPS.Entity;
using AlwaysPPS.Entity.Common;
using AlwaysPPS.Entity.FormatMODEL;
using AlwaysPPS.Entity.StoredProcedure;
using AlwaysPPS.Entity.ViewModel;
using AlwaysPPS.Library;
using AlwaysPPS.Service;
using Kendo.Mvc.UI;
using Microsoft.Practices.Unity;
using System.Data.Linq.SqlClient;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using OfficeOpenXml.Table;
using AlwaysPPS.Library.Constant;
namespace AlwaysPPS.Web.Controllers
{
    public class JuryComparer : IEqualityComparer<HumanResources>
    {
        public bool Equals(HumanResources x, HumanResources y)
        {
            return (x.uid.Equals(y.uid) && x.content.Equals(y.content) && x.dates == y.dates && x.status.Equals(y.status) && x.teamID == y.teamID && x.totalHours.Equals(y.totalHours));
        }
        public int GetHashCode(HumanResources obj) { return 0; }
    }
    public class JuneComparer : IEqualityComparer<Assign>
    {
        public bool Equals(Assign x, Assign y)
        {
            return (x.proName.Equals(y.proName) && x.teamID.Equals(y.teamID));
        }
        public int GetHashCode(Assign obj) { return 0; }
    }
    public class ReportFormController : BaseController
    {

        //DataContext dbPPS=new AlwaysPPSDataEntryDbContext();
        private readonly IReportFormService workPlan;
        private readonly IProjectWorkPlanService iProjectWorkPlanService;
        private readonly ITResourceTeamService _iTResourceTeamService;

        private readonly ICtTeamService _iCtTeamService;

        private readonly IOaDepartment _IOaDepartment;

        private readonly ISpRPTTeamTimeSheetServer _spRptTeamTimeSheetServer;

        private readonly IOaEmployeeService _employeeService;

        private readonly ICtProjectTypeService _ICtProjectTypeService;

        private readonly ISpRPTByTeamTimeSheetServer _rptByTeam;

        private readonly ISpRPTGetTimeSheetByTeamServer _byTeamTimeSheetServer;

        private readonly IProjectService _projectService;

        private readonly IReportCharDataService _charData;

        private readonly IReportDataByClient _client;

        private readonly IReportDataByProject _projectData;

        private readonly IReportDataByDept _deptData;
        //constructor
        public ReportFormController(
                 [Dependency(UnityIOC.UOF.AlwaysPPS)]IUnitOfWork unitOfWork
            , IReportFormService _test
            , IProjectWorkPlanService _IProjectWorkPlanService
            ,  ITResourceTeamService iTResourceTeamService
            , ICtTeamService _iCtTeamService
            , IOaDepartment _IOaDepartment
            , ISpRPTTeamTimeSheetServer _spRptTeamTimeSheetServer
            , IOaEmployeeService _employeeService
            , ICtProjectTypeService _ICtProjectTypeService
            , ISpRPTByTeamTimeSheetServer _rptByTeam
            , ISpRPTGetTimeSheetByTeamServer _byTeamTimeSheetServer
            , IProjectService _projectService
            ,IReportCharDataService _charData
            , IReportDataByClient _client
            , IReportDataByProject _projectData
            , IReportDataByDept _deptData

            )
            : base(unitOfWork)
        {
            this.workPlan = _test;
            this.iProjectWorkPlanService = _IProjectWorkPlanService;
              _iTResourceTeamService = iTResourceTeamService;
            this._iCtTeamService = _iCtTeamService;
            this._IOaDepartment = _IOaDepartment;

            this._spRptTeamTimeSheetServer = _spRptTeamTimeSheetServer;
            this._employeeService = _employeeService;
            this._ICtProjectTypeService = _ICtProjectTypeService;
            this._rptByTeam = _rptByTeam;
            this._byTeamTimeSheetServer = _byTeamTimeSheetServer;
            this._projectService = _projectService;
            this._charData = _charData;
            this._client = _client;
            this._projectData = _projectData;
            this._deptData = _deptData;
        }

        //
        // GET: /ReportForm/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult hrTable()
        {
            BindViewBagUser();
            return View();
        }
        public ActionResult getDepartment()
        {
            var depID = workPlan.getDepID(GetCureentID());
            var list = workPlan.GetDep().Where(u => u.DepartmentId == depID).ToList();
            var zx = new List<department>();
            foreach (var i in list)
            {
                department d = new department();
                d.Text = i.DepartmentName;
                d.Value = i.DepartmentId.ToString();
                zx.Add(d);
            }
            return Json(zx, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetBuheadDepart()
        {
           var res=  _IOaDepartment.GetList();
            if(res.Any())
            {
              var result=  res.Select(u => new SelectListItem() {Text = u.DepartmentName, Value = u.DepartmentId.ToString()});
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult getTeam(string beginTime, string endTime, string department)
        {
            if (beginTime == "" || endTime == "")
            {
                this.ShowNotification(NotificationType.Error, "请填写日期！");
                return null;
            }
            if (department == "")
            {
                this.ShowNotification(NotificationType.Error, "请填写部门！");
                return null;
            }
            try
            {
                var begin = DateTime.Parse(beginTime);
                var end = DateTime.Parse(endTime);
            }
            catch (Exception e)
            {
                this.ShowNotification(NotificationType.Error, "请填写正确日期！");
                return null;
            }

            var teamIDList = workPlan.getTeamID(GetCureentID());
            IDictionary<string, object> Dic = new Dictionary<string, object>();
            SpRPTByTeamParameter sq = new SpRPTByTeamParameter(){FromDate =beginTime,ToDate=endTime,UserDeptId=Convert.ToInt32(department) };

           var zx = _rptByTeam.GetList(sq);
           //= workPlan.GetTeams().Where(u => teamIDList.Contains(u.teamID)).Where(u => u.status == DataStatus.ProjectState.pendingByTeamLeaderEnd || u.status == DataStatus.ProjectState.closed).OrderBy(u=>u.leadID).ToList();
            var group1 = (from u in zx
                          orderby u.lead
                          group u by new { u.lead }
                              into g
                              select new { c = g.Key, d = g.Count() })
                .ToList();
            var group2 = (from u in zx 
                          orderby u.lead
                          group u by new { u.lead, u.name }
                              into g
                              select new { d = g.Count() })
                .ToList();
            Dic.Add("d1", group1);
            Dic.Add("d2", group2);

            // if (beginTime == "") { beginTime = new DateTime(1900, 1, 1).ToString(); }
            //if (endTime == "") { endTime = new DateTime(2900, 1, 1).ToString(); }
            var list = zx.Distinct().OrderBy(ct => ct.lead).ToList();//endTime大于ct.EndTime(页面大于数据库)
            Dic.Add("d3", list);
            if (list.Count == 0)
            {
                this.ShowNotification(NotificationType.Information, "没有信息！");
                return null;
            }
            return Json(Dic, JsonRequestBehavior.AllowGet);
            return View(Dic);
            //return PartialView("tmTable", Dic);
        }
        public ActionResult GetAssign(string beginTime, string endTime, string department)
        {
            if (beginTime == "" || endTime == "")
            {
                this.ShowNotification(NotificationType.Error, "请填写日期！");
                return null;
            }
            if (department == "")
            {
                this.ShowNotification(NotificationType.Error, "请填写部门！");
                return null;
            }
            try
            {
                var begin = DateTime.Parse(beginTime);
                var end = DateTime.Parse(endTime);
            }
            catch (Exception e)
            {
                this.ShowNotification(NotificationType.Error, "请填写正确日期！");
                return null;
            }
            GetTimeSheetParameter gt = new GetTimeSheetParameter() { BeginTime = Convert.ToDateTime(Convert.ToDateTime(beginTime).ToString("yyyy-MM-dd")), EndTime = Convert.ToDateTime(Convert.ToDateTime(endTime).ToString("yyyy-MM-dd")), Dpartment = Convert.ToInt32(department) };
            var res=  _byTeamTimeSheetServer.GetList(gt);
            return Json(res, JsonRequestBehavior.AllowGet);
            
        }

        /// <summary>
        /// Get Current User's department Traffic Leader ID
        /// </summary>
        /// <returns>-1: Traffic Leader Id not found, else: returns Traffic Leader Id</returns>
        private int CurrentUserDepartmentTrafficeLeaderId()
        {
            var userID = -1;

            var oa = _employeeService.GetByUid(User.UserId);
            if (oa != null)
            {
                var res = _IOaDepartment.GetByDepartmentID(oa.DepartmentId.Value);
                if (res != null)
                {
                    //是Buheader
                    if (res.DepartmentHeadUid == User.UserId)
                    {

                        var team = _ICtProjectTypeService.GetByDept(res.DepartmentId);
                        if (team != null)

AlwaysPPS/trunk/AlwaysPPS.Web/Views/ReportForm/ChartReport.cshtml
@{
    ViewBag.Title = "ChartReport";
}
<div class="row">
    <div class="col-md-12 ">
        <div class="titleBar">
            <h3>报表（项目分配）</h3>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="main">
            <div id="searchBar" class="searchBox">
                <form role="form">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-2">
                                
                                <input type="text" class="form-control" 
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value:startDate" 
                                    />
                            </div>
                            <div class="col-md-2">
                                
                                <input type="text" class="form-control" 
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value:endingDate" 
                                    />
                            </div>
                            
                            <div class="col-md-2">
                                <button class="btn btn-blueBlack" data-bind="click: Submit" type="button" style="margin-top: 5px;"><i class="icon-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="chart">
                <div class="chartTitle">项目</div>
                <div id="graphTableEntry" class="chartMain"></div>
            </div>
            <div class="chart">
                <div class="chartTitle">实际消耗时间</div>
                <div id="consumptionTime" class="chartMain"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        var dataSource;
        var searchBarModel = kendo.observable({
            
            startDate: "",
            endingDate: "",

            Submit: function(e) {

                e.preventDefault();


                var searchBar = $("#searchBar").kendoValidator().data("kendoValidator");
                if (!searchBar.validate()) {
                    return false;
                }
                //Save to Server            
                var submitModel = {
                    startDate: this.startDate,
                    endingDate: this.endingDate
                };
                $.ajax({
                    type: 'Post',
                    url: "/ReportForm/GetAssign",
                    data: kendo.stringify(submitModel),
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    success: function(script) {
                        //eval(script);\
                        dataSource = script;
                    }
                });

            }
        });
        kendo.bind($("#searchBar"), searchBarModel);

        $('#graphTableEntry').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: "",
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            global: {
                canvasToolsURL: false
            },
            exporting: {
                buttons: {
                    contextButton: {
                        enabled:false
                    }
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: '项目比例',
                data: [
                    ['A项目', 45.0],
                    ['B项目', 26.8],
                    {
                        name: 'C项目',
                        y: 12.8,
                        sliced: true,
                        selected: true
                    },
                    ['D项目', 8.5],
                    ['E项目', 6.2],
                    ['F项目', 0.7]
                ]
            }]
        });
        $('#consumptionTime').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: "",
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            global: {
                canvasToolsURL: false
            },
            exporting: {
                buttons: {
                    contextButton: {
                        enabled: false
                    }
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: '实际消耗时间',
                //data: [
                //    ['A项目', 45.0],
                //    ['B项目', 26.8],
                //    {
                //        name: 'C项目',
                //        y: 12.8,
                //        sliced: true,
                //        selected: true
                //    },
                //    ['D项目', 8.5],
                //    ['E项目', 6.2],
                //    ['F项目', 0.7]
                //]
                data:dataSource
            }]
        });
    })
</script>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/ReportForm/HumanResource.cshtml
@{
    ViewBag.Title = "报表（人力资源概括）";
}
<div class="row">
    <div class="col-md-12 ">
        <div class="titleBar">
            <h3>报表（人力资源概括）</h3>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="main">
            <div id="searchBar" class="searchBox">
                <form role="form">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label> 开始时间</label><br/>
                                <input type="text" class="form-control" style="width:95%;"
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value: startDate" 
                                       id="beginTime"
                                    />
                            </div>
                            <div class="col-md-4">
                                <label> 结束时间</label><br/>
                                <input type="text" class="form-control" style="width:95%;"
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value: endingDate" 
                                       id="endTime" 
                                    />
                            </div>
                            <div class="col-md-4">
                                <label> 部门</label><br/>
                                <input type="text" class="form-control" style="width:95%;"
                                       data-role="dropdownlist"
                                       data-auto-bind="false"
                                       data-value-primitive="true"
                                       data-option-label="请选择部门"
                                       data-text-field="Text"
                                       data-value-field="Value"
                                       data-bind="source: departments,
    value: department"                  
                                        
                                       id="department"
                                    readonly="readonly"
                                    />
                            </div>
                        </div>
                        <div class="row">
                            @{
                                if(ViewBag.Istraffic=="1")
                                {
                                     <div class="col-md-4">
                                <label> Team</label><br/>
                                   <input type="text" class="form-control" style="width:95%;"
                                       data-role="dropdownlist"
                                       data-auto-bind="false"
                                       data-value-primitive="true"
                                       data-option-label="请选择Team"
                                       data-text-field="Text"
                                       data-value-field="Value"
                                       data-bind="source: team, value: selectTeam" id="selTeam"/>
                            </div>
                                }
                            }
                           
                            <div class="col-md-4">
                                <label> 立项部门</label><br/>
                                <input type="text" class="form-control" style="width:95%;"
                                       data-role="dropdownlist"
                                       data-auto-bind="false"
                                       data-value-primitive="true"
                                       data-option-label="请选择立项部门"
                                       data-text-field="Text"
                                       data-value-field="Value"
                                       data-bind="source: foundedDepartment,
    value: selectFoundedDepartment"                  
                                        
                                     id="buildDepart"  
                                    />
                            </div>
                            <div class="col-md-4 ">
                                
                                <button class="btn btn-blueBlack hyponasty"  id="excels"  data-bind="click: Export" type="button" ><i class="icon-list-alt"></i>&nbsp;&nbsp;导出</button>
                                <button class="btn btn-blueBlack hyponasty" id="searchs" data-bind="click: Submit" type="button" ><i class="icon-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        </div>
                       @* <div class="row">
                            <div class="col-md-4 col-md-offset-8">
                                
                                <button class="btn btn-blueBlack hyponasty"  id="excels"  data-bind="click: Export" type="button" ><i class="icon-list-alt"></i>&nbsp;&nbsp;导出</button>
                                <button class="btn btn-blueBlack hyponasty" id="searchs" data-bind="click: Submit" type="button" ><i class="icon-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        </div>*@
                    </div>
                </form>
            </div>
           

            <div id="searchGrid" class="hrSummaryTableWapper fakeContainer">
                @*<table id="grid" class="table hrSummaryTable table-bordered"></table>*@
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
      
        var departmentsDataSource = new kendo.data.DataSource({
            serverFiltering: true,
            transport: {
                read: {
                    dataType: "json",
                    url: "/ReportForm/getDepartment"
                }
            }
        });
        var teamDataSource = new kendo.data.DataSource({
            serverFiltering: true,
            transport: {
                read: {
                    dataType: "json",
                    url: "/ReportForm/GetTeams"
                }
            }
        });
        var foundedDepartmentDataSource = new kendo.data.DataSource({
            serverFiltering: true,
            transport: {
                read: {
                    dataType: "json",
                    url: "/ReportForm/GetBuheadDepart"
                }
            }
        });
        var searchBarModel = kendo.observable({
            departments: departmentsDataSource,
            team: teamDataSource,
            foundedDepartment: foundedDepartmentDataSource,

            startDate: "",
            endingDate: "",
            department: '@ViewBag.depts',
            selectTeam: null,
            selectFoundedDepartment: null,
            Submit: function (e) {

                e.preventDefault();

                var st = $("#endTime").val();
                var et = $("#endTime").val();
                if (st == "" || et == "") {
                    app.Notification.error("开始或结束时间不能为空！");
                    return false;
                }

                var searchBar = $("#searchBar").kendoValidator().data("kendoValidator");
                if (!searchBar.validate()) {
                    return false;
                }
                //Save to Server            
                //var submitModel = {
                //    beginTime: this.startDate,
                //    endTime: this.endingDate,
                //    department: this.get("department")
                //};
                
                //location.href =@Url.Action("getHumanResource","ReportForm") + "?beginTime" + $("#beginTime").val() + "&endTime=" + $("#endTime").val() + "&department=" + $("#department").val() + "&selTeam=" + $("#selTeam").val() + "&buildDepart=" + $("#buildDepart").val();
               
                $.ajax({
                    type: 'get',
                    url: "/ReportForm/getHumanResource",
                    //data: kendo.stringify(submitModel),
                    data: "beginTime=" + $("#beginTime").val() + "&endTime=" + $("#endTime").val() + "&department=" + $("#department").val() + "&selTeam=" + $("#selTeam").val() + "&buildDepart=" + $("#buildDepart").val(),
                    contentType: "application/json; charset=utf-8",
                    dataType: 'html',
                    cache:false,
                    success: function (script) {
                        //eval(script);
                       
                        $("#searchGrid").html($.trim(script));
                        var contentHeadH = $(window).height() - 430;
                        $(".hrSummaryTableWapper").attr('style', 'height:' + contentHeadH + 'px');
                        var mySt = new superTable("grid", {
                            cssSkin: "sSky",
                            fixedCols: 1,
                            headerRows: 1
                        });
                        structure(60, 220, "menu", "slideArea");
                    },
                    beforeSend:function() {
                        loade();
                    },
                    complete:function() {
                        loadeStop();
                        
                           
                       
                    }
                });

            },
            Export: function (e) {
                if ($("#beginTime").val() == "" || $("#endTime").val() == "") {
                    app.Notification.warning("请填写日期");
                    return false;
                }
                if ($("#department").val() == "") {
                    app.Notification.warning("请填写部门");
                    return false;
                }
                e.preventDefault();
                var searchBar = $("#searchBar").kendoValidator().data("kendoValidator");
                
                if (!searchBar.validate()) {
                    return false;
                } else {
                    location.href = "/ReportForm/SaveToExcelX?beginTime=" + $("#beginTime").val() + "&endTime=" + $("#endTime").val() + "&department=" + $("#department").val() + "&selTeam=" + $("#selTeam").val() + "&buildDepart=" + $("#buildDepart").val();
                }
                //Save to Server            

            }
        });
        kendo.bind($("#searchBar"), searchBarModel);

        //页面跳转
        function JumpDetailPage(e) {
            e.preventDefault();

            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            var accId = dataItem.CallReportId;
            window.location.href = "/Html/ProjectDetails";

        }
        $("#searchGrids").kendoGrid({
            dataSource: {
                type: "odata",
                transport: {
                    read: "http://demos.telerik.com/kendo-ui/service/Northwind.svc/Orders"
                },
                schema: {
                    model: {
                        fields: {
                            OrderID: { type: "number" },
                            ShipCountry: { type: "string" },
                            ShipCity: { type: "string" },
                            ShipName: { type: "string" },
                            OrderDate: { type: "date" },
                            ShippedDate: { type: "date" }
                        }
                    }
                },
                pageSize: 15
            },
            height: 430,
            sortable: true,
            reorderable: true,
            resizable: true,
            pageable: true,
            columns: [
                {
                    field: "OrderDate",
                    title: "Order Date",
                    width: 110,
                    format: "{0:MM/dd/yyyy}"
                },
                {
                    field: "ShipCountry",
                    title: "Ship Country",
                    width: 110
                },
                {
                    field: "ShipCity",
                    title: "Ship City",
                    width: 110
                },
                {
                    field: "ShipName",
                    title: "Ship Name",
                    width: 200
                },
                {
                    field: "ShippedDate",
                    title: "Shipped Date",
                    format: "{0:MM/dd/yyyy}"
                },
                {
                    field: "OrderID",
                    title: "ID",
                    width: 60
                },
                {
                    command: [
                        {
                            name: "",
                            text: "查看详细",
                            imageClass: "k-icon iconB-search ",
                            click: JumpDetailPage
                        }
                    ],
                    width: '10%',
                    attributes: { style: "text-align: center; " }
                }
            ]
        });
    })
</script>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/ReportForm/hrTable.cshtml
@using AlwaysPPS.Entity
@using AlwaysPPS.Entity.StoredProcedure
@{ int num = 0;}

<table id="grid" class="table hrSummaryTable table-bordered">
@if (Model != null)
{

    <thead>
        <tr>
            <th>日期</th>

            @foreach (var i in ((Dictionary<int, string>)Model["d1"]))
            {
                <th>@i.Value</th>
            }
        </tr>
    </thead>
    <tbody>
    @*@{ int index = 0;}*@
    @{List<SpRPTTeamTimeSheet> listData = (List<SpRPTTeamTimeSheet>)ViewBag.pros;}


    @foreach (var i in Model["d2"])
    {
        <tr @{
                if (DateTime.Parse(i).ToString("dddd") == "星期六" || DateTime.Parse(i).ToString("dddd") == "星期日")
                {
                    @Html.Raw("style='background-color:powderblue'")
                }
            }>
            <td>@DateTime.Parse(i).ToString("yyyy/MM/dd")</td>
            @foreach (var e in ((Dictionary<int, string>)Model["d1"]))
            {

                var tempData = listData.Where(d => d.uid == e.Key && d.dates.ToString("yyyy-MM-dd") == Convert.ToDateTime(i).ToString("yyyy-MM-dd"));


                if (tempData.Any()==false)
                {
                    <td></td>
                }
                else
                {
                    <td>
                        @if (tempData.Sum(tx => tx.totalHours) >= 8)
                        {
                            <span class="greenPoint"></span>
                        }
                        else {
                            <span class="redPoint"></span>
                        }
                        <br/>                            
                        <ul>                                
                            @foreach (var h in tempData)
                            {
                                <li>@Html.Raw(h.content)</li>                                
                            }                              
                        </ul>
                    </td>
                }

            }

            @*@{ index++; }*@
        </tr> 
    }
</tbody>

}
</table>