AlwaysPPS/trunk/AlwaysPPS.Web/Controllers/HtmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlwaysFramework.DAL;
using AlwaysPPS.Entity;
using AlwaysPPS.Entity.FormatMODEL;
using AlwaysPPS.Library;
using AlwaysPPS.Service;
using Microsoft.Practices.Unity;

namespace AlwaysPPS.Web.Controllers
{
    public class HtmlController : BaseController
    {
#if DEBUG
            //
        // GET: /Report/
        private readonly IUnitOfWork _unitOfWork;

        private readonly ITResourceTeamService _iTResourceTeamService;
        private readonly ICtProjectTypeService _ICtProjectTypeService;
        private readonly IProjectService _IProjectService;
        private readonly IOaEmployeeService _IOaEmployeeService;
        private readonly OaDepartmentService _OaDepartmentService;
        private readonly ITProjectTaskService _ITProjectTaskService;

        public HtmlController(
            [Dependency(UnityIOC.UOF.AlwaysPPS)]IUnitOfWork unitOfWork
            , ITResourceTeamService iTResourceTeamService
            , ICtProjectTypeService iCtProjectTypeService
            , IProjectService iProjectService
            , IOaEmployeeService iOaEmployeeService
            , OaDepartmentService oaDepartmentService
            , ITProjectTaskService _iTProjectTaskService)
            : base(unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _iTResourceTeamService = iTResourceTeamService;
            
            _ICtProjectTypeService = iCtProjectTypeService;
            _IProjectService = iProjectService;
            _IOaEmployeeService = iOaEmployeeService;
            _OaDepartmentService = oaDepartmentService;
        }


        // GET: /Html/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddNewItem()
        {
            var list = _ICtProjectTypeService.GetTypes();
            if (list.Any())
            {
                var selItems = new List<SelectListItem>();
                foreach (var items in list)
                {
                    if (items != null)
                    {
                        selItems.Add(new SelectListItem() { Text = items.ProjectTypeDesc, Value = items.ProjectTypeId.ToString() });
                    }
                }
                ViewBag.ProType = selItems;
            }
            else
            {
                SelectListItem sel = new SelectListItem();
                ViewBag.ProType = sel;
            }

            return View();
        }

        public ActionResult Milestone()
        {
            return View();
        }

        public ActionResult HumanResourcePlanning()
        {
            return View();
        }

        public ActionResult Folder()
        {
            return View();
        }

        public ActionResult ProjectDetail()
        {



            var list = _ICtProjectTypeService.GetTypes();
            if (list.Any())
            {
                var selItems = new List<SelectListItem>();
                foreach (var items in list)
                {
                    if (items != null)
                    {
                        selItems.Add(new SelectListItem() { Text = items.ProjectTypeDesc, Value = items.ProjectTypeId.ToString() });
                    }
                }
                ViewBag.ProType = selItems;
            }
            else
            {
                SelectListItem sel = new SelectListItem();
                ViewBag.ProType = sel;
            }
            return View();
        }

        //搜索
        public ActionResult  SearchableItems()
        {
            return View();
        }

        public ActionResult ReportOne()
        {
            return View();
        }

        public ActionResult ChartReport()
        {
            return View();
        }

        public  ActionResult GetFullCalendar()
        {
            return View();
        }

        public ActionResult GetFullData()
        {
            //List<FullCalendarModel> res = new List<FullCalendarModel>();
            //FullCalendarModel model = new FullCalendarModel();
            //model.start = Convert.ToDateTime("2014-06-03");
            //model.end = Convert.ToDateTime("2014-06-04");
            //model.title = "今天来打酱油";
            //res.Add(model);
            //ViewBag.Data = res;
            //ViewBag.id = "22";

            //FullCalendarModel model2 = new FullCalendarModel();
            //model2.start = Convert.ToDateTime("2014-06-03");
            //model2.end = Convert.ToDateTime("2014-06-04");
            //model2.title = "今天来打酱油";
            //res.Add(model2);
            //ViewBag.Data = res;
            //ViewBag.id = "22";
            return View();
        }


        public ActionResult GetData()
        {
            //List<FullCalendarModel> res=new List<FullCalendarModel>();
            //FullCalendarModel model=new FullCalendarModel();
            //model.start = DateTime.Now;
            //model.end = DateTime.Now.AddDays(1);
            //model.title = "今天来打酱油";
            //res.Add(model);
            //return Json(res, JsonRequestBehavior.AllowGet);
            return null;
        }
        public ActionResult HourExplain()
        {
            return View();
        }
#endif 
    }
}

AlwaysPPS/trunk/AlwaysPPS.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlwaysFramework.DAL;
using AlwaysFramework.MVC;
using AlwaysFramework.MVC.Extension;
using AlwaysPPS.Entity.StoredProcedure;
using AlwaysPPS.Library;
using AlwaysPPS.Service;
using Kendo.Mvc.UI;
using Microsoft.Practices.Unity;

namespace AlwaysPPS.Web.Controllers
{
    public class SearchController : BaseController
    {
        //
        // GET: /Search/

           private readonly IProjectService _projectService;
        private readonly OaDepartmentService oaDepartmentService;
        public SearchController([Dependency(UnityIOC.UOF.AlwaysPPS)]IUnitOfWork unitOfWork, IProjectService projectService, OaDepartmentService _oaDepartmentService)
            : base(unitOfWork)
        {
            _projectService = projectService;
            oaDepartmentService = _oaDepartmentService;
        }

        public ActionResult SearchProjects()
        {
            BindViewBagUser();
            return View();
        }
        [HttpPost]
        public ActionResult SearchProjects(SearchParameter parameter)
        {
            try
            {
                int PageIndex = parameter.PageIndex.HasValue ? parameter.PageIndex.Value : 1;
                int RowSize = parameter.NumRow.HasValue ? parameter.NumRow.Value : 15;
                parameter.PageIndex = PageIndex;
                parameter.NumRow = RowSize;

                parameter.userId = User.UserId;
                var model = _projectService.SearchProjects(parameter);
                if (model.Count == 0)
                {
                    this.ShowNotification(NotificationType.Error, "无数据");
                }
                //return Json(model);
                DataSourceResult data = new DataSourceResult();
                //data.AggregateResults = null;//
                //data.Errors = "";//
                foreach (var item in model)
                {
                    var res = oaDepartmentService.GetByDepartmentID(item.DepartmentId);
                    if(res!=null)
                    {
                        item.DeptName = res.DepartmentName;
                    }
                    if(item.Deadline<=DateTime.Now)
                    {
                        item.IsChaoShi = true;
                    }
                    else
                    {
                        if(item.Deadline.Value.Subtract(DateTime.Now).TotalHours<=48)
                        {
                            item.IsChaoShi = true;
                        }
                        else
                        {
                            item.IsChaoShi = false;
                        }
                    }
                }
                data.Data = model;
                data.Total = model.Count != 0 ? model[0].TotalCount : 0;

                return Json(data);

            }
            catch (Exception ex)
            {
                this.ShowNotification(NotificationType.Error, ex.Message);
                return Json(null);
            }
        }

        #region 下拉列表

        public ActionResult GetProjectCodeList()
        {
            var model = _projectService.GetProjectCodeAll();

            List<SelectListItem> Items = new List<SelectListItem>();
            foreach(var e in model)
            {
                Items.Add(new SelectListItem()
                {
                    Text = e,Value=e
                });
            }

            return Json(Items,JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetProjectCodeListByid(string name)
        {
            string nametmp = Request.Params["client"];
            var model = _projectService.GetProjectCodeAllByID(nametmp).Distinct().ToList();

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetClientNameList()
        {
            var model = _projectService.GetClientNameAll();

            List<SelectListItem> Items = new List<SelectListItem>();
            foreach(var e in model)
            {
                Items.Add(new SelectListItem()
                {
                    Text = e,Value = e
                });
            }

            return Json(Items, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetStatusCodeList()
        {
            var model = _projectService.GetStatusAll();

            List<SelectListItem> Items = new List<SelectListItem>();
            foreach(var e in model)
            {
                Items.Add(new SelectListItem()
                {
                    Text = con(e),
                    Value = e
                });
            }

            return Json(Items, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetStateList()
        {
            var model = _projectService.GetStateAll();

            List<SelectListItem> Items = new List<SelectListItem>();
            foreach (var e in model)
            {
                Items.Add(new SelectListItem()
                {
                    Text = e,Value = e
                });
            }

            return Json(Items, JsonRequestBehavior.AllowGet);
        }

        private string con(string val)
        {
            if (val == "A") return "正常";
            else if (val == "C") return "已关闭";
            else return "已删除";
        }
        #endregion



    }
}

AlwaysPPS/trunk/AlwaysPPS.Web/Views/Html/AddNewItem.cshtml
@{
    ViewBag.Title = "AddNewItem";
    var ptSource = ViewBag.ProType as List<SelectListItem>;
}


<div class="row">
    <div class="col-md-12 ">
        <div class="titleBar">
            <h3>新增项目</h3>
        </div>
        <div class="subTitleBar" style="display: none">
            <div class="row">
                <div class="col-md-3">
                    <b class="title">项目编号：</b>
                    <span class="details">2014020501</span>
                </div>
                <div class="col-md-3">
                    <b class="title">创建日期：</b>
                    <span class="details">20140205</span>
                </div>
                <div class="col-md-3">
                    <b class="title">创建人：</b>
                    <span class="details">Hankiong</span>
                </div>
            </div>
        </div>
        <div class="main">
            <div id="addNewItem" class="addNewItemBox">
                <form role="form">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label>项目名称</label>
                                <input id="proName" type="text" class="form-control"
                                       data-auto-bind="false"
                                       data-bind="value: projectName" 
                                    />
                            </div>
                            <div class="col-md-2">
                                <label >客&nbsp;&nbsp;&nbsp;&nbsp;户</label>
                                <input id="kehu" type="text" class="form-control" id="clientName"
                                       data-role="autocomplete"
                                       data-auto-bind="false"
                                       data-bind="source: clients,
                                                    value: client" 
                                    />
                            </div>
                            <div class="col-md-2">
                                <label>项目类别</label>

                                 <select id="projectTypeID"
                                         
                                         data-role="dropdownlist"
                                         data-auto-bind="false"
                                         data-value-primitive="true"
                                         data-option-label="请选择类别"
                                         data-text-field="Text"
                                         data-value-field="Value"
                                         data-bind="value: projectType,
                                            source: projectTypes" >
                                    </select>

                            </div>
                            <div class="col-md-2">
                                <label >部&nbsp;&nbsp;&nbsp;&nbsp;门</label>


                                <select  
                                         data-cascade-from="projectTypeID"
                                         data-role="dropdownlist"
                                         data-auto-bind="false"
                                         data-value-primitive="true"
                                         data-option-label="请选择部门"
                                         data-text-field="Text"
                                         data-value-field="Value"
                                         data-bind="value: department,
                                               source: depts" >
                               </select>
                            </div>
                           
                            <div class="col-md-2">
                                <label>期&nbsp;&nbsp;&nbsp;&nbsp;限</label>
                                <input id="qixian" class="form-control" 
                                       data-role="datepicker"
                                       data-bind="value: deadline"
                                    />                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>项目介绍</label>
                        <textarea id="xmjs" class="form-control" rows="3" data-auto-bind="false" data-bind="value: projectIntroduction"></textarea>
                    </div>
                    <div class="buttonTeam">
                        <button class="btn btn-blueBlack" data-bind="click: Submit" type="button"><i class="icon-ok-sign"></i>&nbsp;&nbsp;提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        kendo.culture("zh-CN");
        var clientsDataSource = new kendo.data.DataSource({
            serverFiltering: true,
            type: "aspnetmvc-ajax",
            transport: {
                read: {
                    dataType: "json",
                    url: "/Report/GetClient",
                    data: function () {
                        var keyword = $("#clientName").data("kendoAutoComplete").value() || "";
                        return { client: keyword };
                    }
                }
            }
        });




        var departmentDataSource = new kendo.data.DataSource({
            serverFiltering: true,
            transport: {
                read: {
                    dataType: "json",
                    url: "/Report/GetDepart",
                    data: function() {
                        return {projectTypeID:$("#projectTypeID").val()}
                    },
                }
            }
        });


        var addNewItemModel = kendo.observable({
            clients: clientsDataSource,
            departments: departmentDataSource,
            projectTypes: @Html.Raw(Json.Encode(ptSource)),
            depts: departmentDataSource,
            projectName: null,
            department:null,
            client: null,
            projectType: null,
            deadline: null,
            projectIntroduction: null,
            isPrimitive: false,
            
           

            Submit: function (e) {

                e.preventDefault();



                var editTraining = $("#addNewItem").kendoValidator().data("kendoValidator");
                if (!editTraining.validate()) {
                    return false;
                }
                //Save to Server            
                var SubmitModel = {
                    projectName: this.projectName,
                    client: this.client,
                    department: this.get("department"),
                    projectType: this.get("projectType"),
                    deadline: this.deadline,
                    projectIntroduction: this.projectIntroduction,
                };
             
                app.Notification.success("from view");
                $.ajax({
                    type: 'Post',
                    url: "/Report/Add",
                    data: kendo.stringify(SubmitModel),
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    success: function (script) {
                     //eval(script);
                    }
                });
           
            },
        });
        kendo.bind($("#addNewItem"), addNewItemModel);
    })
</script>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/Html/ChartReport.cshtml
@{
    ViewBag.Title = "ChartReport";
}
<div class="row">
    <div class="col-md-12 ">
        <div class="titleBar">
            <h3>报表（项目分配）</h3>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="main">
            <div id="searchBar" class="searchBox">
                <form role="form">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-2">
                                
                                <input type="text" class="form-control" 
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value:startDate" 
                                    />
                            </div>
                            <div class="col-md-2">
                                
                                <input type="text" class="form-control" 
                                       data-role="datepicker"
                                       data-auto-bind="false"
                                       data-bind="value:endingDate" 
                                    />
                            </div>
                            
                            <div class="col-md-2">
                                <button class="btn btn-blueBlack" data-bind="click: Submit" type="button" style="margin-top: 5px;"><i class="icon-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="chart">
                <div class="chartTitle">项目</div>
                <div id="graphTableEntry" class="chartMain"></div>
            </div>
            <div class="chart">
                <div class="chartTitle">实际消耗时间</div>
                <div id="consumptionTime" class="chartMain"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        var dataSource;
        var searchBarModel = kendo.observable({
            
            startDate: "",
            endingDate: "",

            Submit: function(e) {

                e.preventDefault();


                var searchBar = $("#searchBar").kendoValidator().data("kendoValidator");
                if (!searchBar.validate()) {
                    return false;
                }
                //Save to Server            
                var submitModel = {
                    startDate: this.startDate,
                    endingDate: this.endingDate
                };
                $.ajax({
                    type: 'Post',
                    url: "/ReportForm/GetAssign",
                    data: kendo.stringify(submitModel),
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    success: function(script) {
                        //eval(script);\
                        dataSource = script;
                    }
                });

            }
        });
        kendo.bind($("#searchBar"), searchBarModel);

        $('#graphTableEntry').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: "",
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            global: {
                canvasToolsURL: false
            },
            exporting: {
                buttons: {
                    contextButton: {
                        enabled:false
                    }
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: '项目比例',
                data: [
                    ['A项目', 45.0],
                    ['B项目', 26.8],
                    {
                        name: 'C项目',
                        y: 12.8,
                        sliced: true,
                        selected: true
                    },
                    ['D项目', 8.5],
                    ['E项目', 6.2],
                    ['F项目', 0.7]
                ]
            }]
        });
        $('#consumptionTime').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: "",
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            global: {
                canvasToolsURL: false
            },
            exporting: {
                buttons: {
                    contextButton: {
                        enabled: false
                    }
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                type: 'pie',
                name: '实际消耗时间',
                //data: [
                //    ['A项目', 45.0],
                //    ['B项目', 26.8],
                //    {
                //        name: 'C项目',
                //        y: 12.8,
                //        sliced: true,
                //        selected: true
                //    },
                //    ['D项目', 8.5],
                //    ['E项目', 6.2],
                //    ['F项目', 0.7]
                //]
                data:dataSource
            }]
        });
    })
</script>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/Html/HumanResourcePlanning.cshtml
@{
    ViewBag.Title = "HumanResourcePlanning";
    Layout = null;
}

<h2>HumanResourcePlanning</h2>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/Html/Index.cshtml
@using Antlr.Runtime.Misc
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-12 ">
        <div class="homeBox">
            <div id="tabstrip">
                <ul>
                    <li class="k-state-active">
                        <div class="homeHead">
                            <span class="icons-backlog"></span>
                            待办事宜
                        </div>
                    </li>
                    <li>
                        <div class="homeHead">
                            <span class="icons-myTimetable"></span>
                            我的时间表
                        </div>
                    </li>
                    <li>
                        <div class="homeHead">
                            <span class="icons-myProjects"></span>
                            我的项目
                        </div>
                    </li>
                </ul>
                <div>
                    <div class="titleBar">
                        <h3>待办事宜</h3>
                    </div>
                    <div class="main">
                        @*<div id="trainingItem"></div>*@
                         @Html.Partial("TodoProjects")
                        @*@Html.Action("TodoProjects","Html")*@
                    </div>
                </div>
                <div>
                    <div class="titleBar">
                        <h3>我的时间表</h3>
                    </div>
                    <div class="main">
                        <p>Sunny weather in New York.</p>
                    </div>
                </div>
                <div>
                    <div class="titleBar">
                        <h3>我的项目</h3>
                    </div>
                    <div class="main">
                         @*@Html.Action("MyProject","Html")*@
                        @Html.Partial("MyProject");
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


 <script>
     $(function () {
         //Tab
         $("#tabstrip").kendoTabStrip({
             animation: {
                 open: {
                     effects: "fadeIn"
                 }
             }
         });
     });
</script>

AlwaysPPS/trunk/AlwaysPPS.Web/Views/Html/SearchProjects.cshtml
@{
    ViewBag.Title = "SearchProjects";
}


<div id="SearchItem"></div>
<script>
    $(function () {
        function JumpDetailPage(e) {
            e.preventDefault();

            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            var accId = dataItem.ProjectId;
            window.location.href = "/Html/ProjectDetail?ProjectId=" + accId;

        }

        $("#SearchItem").kendoGrid({
            dataSource: {
                serverFiltering: true,
                serverPaging: true,
                type: "aspnetmvc-ajax",
                transport: {
                    read: {
                        url: '@Url.Action("SearchProjects", "Search")',
                        data: function (data) {
                            return {
                                PageIndex: data.page,
                                NumRow: data.take,
                                //ProjectCode: $("#ProjectCode").val(),
                                //ClientName: $("#ClientName").val(),
                                //Status: $("#Status").val()
                                ProjectCode: null,
                                ClientName: null,
                                Status: "A"
                            };
                        }
                    },
                    dataType: "json",
                    type: "POST"
                },
                pageSize: 15
            },
            //height:800,
            //sortable: true,
            //reorderable: true,
            resizable: true,
            pageable: false,
            columns: [
                 {
                     command: [
                         {
                             name: "",
                             text: "查看详细",
                             imageClass: "k-icon iconB-search ",
                             click: JumpDetailPage
                         }
                     ],
                     width: '20%',

                 },
                {
                    field: "ProjectCode",
                    title: "项目编号",
                    width: '40%'
                },
                {
                    field: "ProjectName",
                    title: "项目名称",
                    width: '40%'
                },
                {
                    field: "ClientName",
                    title: "客户",
                    width: '40%'
                },
                {
                    field: "DeadlineF",
                    title: "项目完稿/比稿日期",
                    width: '30%'
                },
                {
                    field: "StatusF",
                    title: "状态",
                    width: '20%'
                },
                {
                    field: "RequestorName",
                    title: "创建人",
                    width: '30%'
                },
                {
                    field: "RequestedDateF",
                    title: "创建时间",
                    width: '30%'
                }
            ]
            //editable: true
        });
    });
</script>